server:
  port: 11000

spring:
  boot:
    admin:
      register-once: false
      context-path: /

eureka:
  client:
    healthcheck:
      enabled: true

logging:
  file: ${user.dir}/logs/admin.log
  level:
    uy.com.antel.logan: INFO
    com.netflix: ERROR
    org.springframework: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  config:
    activate:
      on-profile: testing

logging:
  file: /var/log/logan/admin.log

---
spring:
  config:
    activate:
      on-profile: produccion

logging:
  file: /var/log/logan/admin.log
